USE [ElysiaLopezBattleships2017]
GO
/****** Object:  Table [dbo].[Shots]    Script Date: 8/28/2017 3:00:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Shots](
	[ShotID] [int] NOT NULL,
	[X] [int] NOT NULL,
	[Y] [int] NOT NULL,
	[isHit] [bit] NOT NULL,
 CONSTRAINT [PK_Shots] PRIMARY KEY CLUSTERED 
(
	[ShotID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
